services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
  